//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelImage.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabelImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Save Mode 的本地化字符串。
        /// </summary>
        public static string AutoSaveMode {
            get {
                return ResourceManager.GetString("AutoSaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Box Line Color 的本地化字符串。
        /// </summary>
        public static string BoxLineColor {
            get {
                return ResourceManager.GetString("BoxLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Save Directory 的本地化字符串。
        /// </summary>
        public static string ChangeSaveDirectory {
            get {
                return ResourceManager.GetString("ChangeSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Image 的本地化字符串。
        /// </summary>
        public static string CloseImage {
            get {
                return ResourceManager.GetString("CloseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Rectangle Box 的本地化字符串。
        /// </summary>
        public static string CreateRectangleBox {
            get {
                return ResourceManager.GetString("CreateRectangleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Rectangle Box 的本地化字符串。
        /// </summary>
        public static string DeleteRectangleBox {
            get {
                return ResourceManager.GetString("DeleteRectangleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Square 的本地化字符串。
        /// </summary>
        public static string DrawSquare {
            get {
                return ResourceManager.GetString("DrawSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate Rectangle Box 的本地化字符串。
        /// </summary>
        public static string DuplicateRectangleBox {
            get {
                return ResourceManager.GetString("DuplicateRectangleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EditLabel 的本地化字符串。
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Window 的本地化字符串。
        /// </summary>
        public static string FitWindow {
            get {
                return ResourceManager.GetString("FitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Rectangle Box 的本地化字符串。
        /// </summary>
        public static string HideRectangleBox {
            get {
                return ResourceManager.GetString("HideRectangleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Image 的本地化字符串。
        /// </summary>
        public static string NextImage {
            get {
                return ResourceManager.GetString("NextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Annotation 的本地化字符串。
        /// </summary>
        public static string OpenAnnotation {
            get {
                return ResourceManager.GetString("OpenAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Directory 的本地化字符串。
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Image 的本地化字符串。
        /// </summary>
        public static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Recent 的本地化字符串。
        /// </summary>
        public static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Size 的本地化字符串。
        /// </summary>
        public static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pascal VOC Format 的本地化字符串。
        /// </summary>
        public static string PascalVOCFormat {
            get {
                return ResourceManager.GetString("PascalVOCFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Image 的本地化字符串。
        /// </summary>
        public static string PrevisouImage {
            get {
                return ResourceManager.GetString("PrevisouImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Current Image 的本地化字符串。
        /// </summary>
        public static string ResetCurrentImage {
            get {
                return ResourceManager.GetString("ResetCurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Annotated Image 的本地化字符串。
        /// </summary>
        public static string SaveAnnotatedImage {
            get {
                return ResourceManager.GetString("SaveAnnotatedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Annotation 的本地化字符串。
        /// </summary>
        public static string SaveAnnotation {
            get {
                return ResourceManager.GetString("SaveAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Labels 的本地化字符串。
        /// </summary>
        public static string ShowLabels {
            get {
                return ResourceManager.GetString("ShowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Rectangle Box 的本地化字符串。
        /// </summary>
        public static string ShowRectangleBox {
            get {
                return ResourceManager.GetString("ShowRectangleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SingleClassMode 的本地化字符串。
        /// </summary>
        public static string SingleClassMode {
            get {
                return ResourceManager.GetString("SingleClassMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yolo Format 的本地化字符串。
        /// </summary>
        public static string YoloFormat {
            get {
                return ResourceManager.GetString("YoloFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom In 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Out 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
